# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from search.models.search_config_schema_attribute import SearchConfigSchemaAttribute
from search.models.search_config_schema_facet import SearchConfigSchemaFacet
from search.models.search_config_schema_filter import SearchConfigSchemaFilter
from search.models.search_config_schema_searchable import SearchConfigSchemaSearchable
from search.models.search_config_schema_sortable import SearchConfigSchemaSortable
from typing import Optional, Set
from typing_extensions import Self

class SearchConfigSchema(BaseModel):
    """
    contains index configurations fields
    """ # noqa: E501
    index: StrictStr = Field(description="index name, to create or where update configuration")
    document_key_name: Optional[StrictStr] = Field(default=None, description="field which value will be used as document id [#DOCGENBUG REQUIRED FIELD]", alias="documentKeyName")
    attributes: List[SearchConfigSchemaAttribute] = Field(description="fields that can be stored into index and later retrieved")
    searchables: Optional[List[SearchConfigSchemaSearchable]] = Field(default=None, description="fields that can be used for fulltext searches")
    facets: Optional[List[SearchConfigSchemaFacet]] = Field(default=None, description="fields that can be used for aggregations")
    filters: Optional[List[SearchConfigSchemaFilter]] = Field(default=None, description="fields that can be used for filtering")
    sortables: Optional[List[SearchConfigSchemaSortable]] = Field(default=None, description="fields that can be used for sorting")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["index", "documentKeyName", "attributes", "searchables", "facets", "filters", "sortables"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchConfigSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in searchables (list)
        _items = []
        if self.searchables:
            for _item_searchables in self.searchables:
                if _item_searchables:
                    _items.append(_item_searchables.to_dict())
            _dict['searchables'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in facets (list)
        _items = []
        if self.facets:
            for _item_facets in self.facets:
                if _item_facets:
                    _items.append(_item_facets.to_dict())
            _dict['facets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sortables (list)
        _items = []
        if self.sortables:
            for _item_sortables in self.sortables:
                if _item_sortables:
                    _items.append(_item_sortables.to_dict())
            _dict['sortables'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchConfigSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index": obj.get("index"),
            "documentKeyName": obj.get("documentKeyName"),
            "attributes": [SearchConfigSchemaAttribute.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "searchables": [SearchConfigSchemaSearchable.from_dict(_item) for _item in obj["searchables"]] if obj.get("searchables") is not None else None,
            "facets": [SearchConfigSchemaFacet.from_dict(_item) for _item in obj["facets"]] if obj.get("facets") is not None else None,
            "filters": [SearchConfigSchemaFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "sortables": [SearchConfigSchemaSortable.from_dict(_item) for _item in obj["sortables"]] if obj.get("sortables") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


