# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.search_config_schema_facet import SearchConfigSchemaFacet

class TestSearchConfigSchemaFacet(unittest.TestCase):
    """SearchConfigSchemaFacet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchConfigSchemaFacet:
        """Test SearchConfigSchemaFacet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchConfigSchemaFacet`
        """
        model = SearchConfigSchemaFacet()
        if include_optional:
            return SearchConfigSchemaFacet(
                attribute = ''
            )
        else:
            return SearchConfigSchemaFacet(
                attribute = '',
        )
        """

    def testSearchConfigSchemaFacet(self):
        """Test SearchConfigSchemaFacet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
