# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.param_sort_order import ParamSortOrder

class TestParamSortOrder(unittest.TestCase):
    """ParamSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParamSortOrder(self):
        """Test ParamSortOrder"""
        # inst = ParamSortOrder()

if __name__ == '__main__':
    unittest.main()
