# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.search_param_facet_type import SearchParamFacetType

class TestSearchParamFacetType(unittest.TestCase):
    """SearchParamFacetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchParamFacetType(self):
        """Test SearchParamFacetType"""
        # inst = SearchParamFacetType()

if __name__ == '__main__':
    unittest.main()
