# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.search_query_request_type import SearchQueryRequestType

class TestSearchQueryRequestType(unittest.TestCase):
    """SearchQueryRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchQueryRequestType(self):
        """Test SearchQueryRequestType"""
        # inst = SearchQueryRequestType()

if __name__ == '__main__':
    unittest.main()
