# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.search_param_filter_type import SearchParamFilterType

class TestSearchParamFilterType(unittest.TestCase):
    """SearchParamFilterType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchParamFilterType(self):
        """Test SearchParamFilterType"""
        # inst = SearchParamFilterType()

if __name__ == '__main__':
    unittest.main()
