# coding: utf-8

"""
    Search Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search.models.search_config_schema_attribute_type import SearchConfigSchemaAttributeType

class TestSearchConfigSchemaAttributeType(unittest.TestCase):
    """SearchConfigSchemaAttributeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchConfigSchemaAttributeType(self):
        """Test SearchConfigSchemaAttributeType"""
        # inst = SearchConfigSchemaAttributeType()

if __name__ == '__main__':
    unittest.main()
